### PR TITLE
Override completion from M73 progress

### PR DESCRIPTION
**Pull request by sabaatworld**
This change overrides the progress percentage displayed in the web interface and apps with the value reported by the printer in response to the M73 command.

### CODE REVIEW

**Comment by sabaatworld** [comment]
Would you be willing to merge this in?

**Comment by kanocz** [comment]
@sabaatworld sorry, missed your first message
question: how does this change really help? I have no prusa printer anymore, so I'm not using this plugin anymore, but had no problems with original one... why we need to set `progressCallBack` ?

**Comment by sabaatworld** [comment]
Hi. This change uses the progress percentage extracted from the printer's response and shows that up for in OctoPrint. Without this change, although the ETA is correct, the percentage completion is not correct cause OctoPrint uses file progress for estimation. Since there is no API to report progress from plugins, I override that method to apply the percentage when print is in progress. This idea is based on Progress based on time plugin.

**Comment by kanocz** [comment]
ok, super

**Comment by sabaatworld** [comment]
Do you know when you plan to make the next plug-in version release?

**Comment by kanocz** [comment]
just done :)

**Comment by sabaatworld** [comment]
Thanks!

**Comment by arekm** [comment]
@sabaatworld Sadly it caused regression
https://github.com/arekm/octopi_eta_override/issues/16
so there is a new way of implementing this (overriding progress bar in js only).

Could test if it works for you, too?
https://github.com/arekm/octopi_eta_override/archive/devel.zip

"apps" part is a problem for which I don't see a great solution other than fixing octoprint to have separate
time and file position progress.

**Comment by sabaatworld** [comment]
The plug-in from where I had got the idea also included a JS and CSS component that I could not figure out before. Maybe it's for fixing issues like this. I'll look into that part when I get time.

**Pull request merged**
