### PR TITLE
Use silent mode estimates

### PR DESCRIPTION
**Pull request by hergtoler**
Defaults to using silent mode time estimate
Custom firmware with M-code to query silent mode status allow this to change automatically

### CODE REVIEW

**Comment by kanocz** [comment]
this commit default to silent mode and manual editing of code required to change back to normal... I don't think it's good solution as 90% of users will not able to do this and most of them don't print in silent mode :( this can be acceptable only in case of configuration via UI

**Comment by hergtoler** [comment]
It will change to normal or silent automatically when the printer outputs 'SILENT MODE: DISABLED' or 'SILENT MODE: ENABLED'.  That output is not in the stock Prusa firmware, however, and there is no output that would let octopi know what mode it is in, so I agree that directly apply this does not fix the problem.  I've since submitted this pull request (https://github.com/prusa3d/Prusa-Firmware/pull/2735) that would allow octopi to figure it out, but it has not been merged.

**Comment by arekm** [comment]
This one can be closed since https://github.com/kanocz/octopi_eta_override/pull/13 was merged and https://github.com/prusa3d/Prusa-Firmware/pull/2735 is a better solution for Prusa Firmware than custom M919.

**Comment by kanocz** [comment]
@arekm sure, thank you
closed due #13 merged

**Pull request closed without merging**
